spring:
  application:
    name: delivery

  # DB 연결 — 3-3의 docker run 값과 똑같이
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: ${DB_USERNAME:delivery}
    password: ${DB_PASSWORD}

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}